import type { WealthData } from "./types";

export const demoData: WealthData = {
  profile: {
    name: "Huzaifa",
    baseCurrency: "USD",
    targetMonthlySavings: 2500,
    riskStyle: "Balanced",
  },
  flows: [
    {
      id: "flow-emergency",
      name: "Emergency Reserve",
      category: "Savings",
      description: "Liquid savings across bank and money market pools.",
    },
    {
      id: "flow-equities",
      name: "Long-term Equities",
      category: "Stocks",
      description: "Brokerage positions and recurring index investments.",
    },
    {
      id: "flow-property",
      name: "Property Fund",
      category: "Real Estate",
      description: "Capital reserved for future property purchases.",
    },
  ],
  pools: [
    {
      id: "pool-bank",
      flowId: "flow-emergency",
      name: "High Yield Bank",
      kind: "savings",
      netContributions: 12000,
      portfolioValue: 12380,
      notes: "Main liquid buffer.",
    },
    {
      id: "pool-money-market",
      flowId: "flow-emergency",
      name: "Money Market",
      kind: "cash",
      netContributions: 6000,
      portfolioValue: 6125,
      notes: "Short dated treasury exposure.",
    },
    {
      id: "pool-index",
      flowId: "flow-equities",
      name: "Index ETF",
      kind: "investment",
      netContributions: 18000,
      portfolioValue: 20750,
      notes: "Monthly contribution plan.",
    },
    {
      id: "pool-growth",
      flowId: "flow-equities",
      name: "Growth Basket",
      kind: "investment",
      netContributions: 8000,
      portfolioValue: 7350,
      notes: "Higher volatility satellite pool.",
    },
    {
      id: "pool-property-cash",
      flowId: "flow-property",
      name: "Down Payment Cash",
      kind: "savings",
      netContributions: 22000,
      portfolioValue: 22420,
      notes: "Capital preservation first.",
    },
  ],
  events: [
    {
      id: "event-1",
      flowId: "flow-equities",
      poolId: "pool-index",
      type: "cash_in",
      amount: 1500,
      note: "Monthly index purchase.",
      happenedAt: "2026-06-01",
    },
    {
      id: "event-2",
      flowId: "flow-equities",
      poolId: "pool-growth",
      type: "info_update",
      field: "portfolioValue",
      newValue: 7350,
      note: "Marked to latest brokerage value.",
      happenedAt: "2026-06-08",
    },
    {
      id: "event-3",
      flowId: "flow-emergency",
      poolId: "pool-bank",
      type: "cash_out",
      amount: 500,
      note: "Medical bill reimbursement.",
      happenedAt: "2026-05-18",
    },
  ],
  transfers: [
    {
      id: "transfer-1",
      flowId: "flow-emergency",
      fromPoolId: "pool-bank",
      toPoolId: "pool-money-market",
      amount: 1500,
      note: "Moved idle cash to higher yield.",
      happenedAt: "2026-05-22",
    },
  ],
};
